name: Update Content from Backend Dispatch

on:
  repository_dispatch:
    types: [daily-updated]
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'
  push:
    branches: [main]

env:
  TZ: Asia/Shanghai

jobs:
  update-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Clone source repository
        uses: actions/checkout@v4
        with:
          repository: 'april8000/ai-insight-daily-token'
          ref: 'main'
          path: 'source-repo'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Process content with inline category tags
        run: |
          echo "ðŸ” å¼€å§‹å¤„ç†å¸¦å†…è”åˆ†ç±»æ ‡ç­¾çš„å†…å®¹..."
          
          # ç¡®ä¿ç›®æ ‡ç›®å½•å­˜åœ¨
          mkdir -p content/cn
          
          # åˆ›å»ºæˆ–æ›´æ–°ä¸»é¡µ
          cat > content/cn/_index.md << 'EOF'
          ---
          title: AIæ´žå¯Ÿæ—¥æŠ¥
          type: docs
          sidebar:
            open: true
          ---
          
          # AIæ´žå¯Ÿæ—¥æŠ¥
          
          æ¬¢è¿Žæ¥åˆ°AIæ´žå¯Ÿæ—¥æŠ¥ï¼è¿™é‡Œä¸ºæ‚¨æä¾›æ¯æ—¥ç²¾é€‰çš„AIèµ„è®¯å’Œæ·±åº¦åˆ†æžã€‚
          
          ## æœ€æ–°æ—¥æŠ¥
          
          æµè§ˆå·¦ä¾§çš„æ—¥æœŸå¯¼èˆªæŸ¥çœ‹æœ€æ–°çš„AIæ—¥æŠ¥å†…å®¹ã€‚
          EOF
          
          # å¤„ç†æ—¥æŠ¥æ–‡ä»¶åˆ°cnç›®å½•
          find source-repo/daily -maxdepth 1 -type f -name "*.md" 2>/dev/null | while read -r SOURCE_FILE_PATH; do
            if [ -f "$SOURCE_FILE_PATH" ]; then
              FILENAME=$(basename "$SOURCE_FILE_PATH")
              DATE_PART=$(echo "$FILENAME" | sed -E 's/([0-9]{4}-[0-9]{2}-[0-9]{2}).*/\1/')
              YEAR_MONTH=$(echo "$DATE_PART" | cut -c1-7)
              
              # æŒ‰çŽ°æœ‰ç»“æž„åˆ›å»ºç›®å½• content/cn/YYYY-MM/
              TARGET_DIR="content/cn/${YEAR_MONTH}"
              mkdir -p "$TARGET_DIR"
              TARGET_FILE="${TARGET_DIR}/${FILENAME}"
              
              echo "--- å¤„ç†æ–‡ä»¶: ${FILENAME} â†’ ${TARGET_FILE} ---"
              
              # æ£€æŸ¥æ˜¯å¦éœ€è¦æ›´æ–°
              NEEDS_UPDATE=true
              if [ -f "$TARGET_FILE" ]; then
                SOURCE_CONTENT=$(cat "$SOURCE_FILE_PATH" 2>/dev/null || echo "")
                TARGET_CONTENT=$(tail -n +20 "$TARGET_FILE" 2>/dev/null || echo "")
                if [ "$SOURCE_CONTENT" = "$TARGET_CONTENT" ]; then
                  echo "æ–‡ä»¶å†…å®¹ç›¸åŒï¼Œè·³è¿‡æ›´æ–°"
                  NEEDS_UPDATE=false
                fi
              fi
              
              if [ "$NEEDS_UPDATE" = true ]; then
                # è¯»å–å†…å®¹è¿›è¡Œæ™ºèƒ½åˆ†æž
                CONTENT=$(cat "$SOURCE_FILE_PATH")
                
                # æ ¹æ®å†…å®¹åˆ†æžç”Ÿæˆåˆ†ç±»æ ‡ç­¾
                CATEGORY_TAGS=""
                
                # åŸºç¡€æ ‡ç­¾
                CATEGORY_TAGS="\`AIèµ„è®¯\` | \`æ¯æ—¥æ—©è¯»\`"
                
                # æ ¹æ®å†…å®¹æ·»åŠ ç‰¹å®šåˆ†ç±»æ ‡ç­¾
                if echo "$CONTENT" | grep -qi "OpenAI\|ChatGPT\|GPT"; then
                  CATEGORY_TAGS="${CATEGORY_TAGS} | \`å¤§æ¨¡åž‹å‰æ²¿\`"
                fi
                if echo "$CONTENT" | grep -qi "æŠ•èµ„\|èžèµ„\|IPO\|ä¸Šå¸‚\|äº¿ç¾Žå…ƒ\|ä¼°å€¼"; then
                  CATEGORY_TAGS="${CATEGORY_TAGS} | \`å•†ä¸šåŠ¨æ€\`"
                fi
                if echo "$CONTENT" | grep -qi "å¼€æº\|GitHub\|ä»£ç \|å¼€å‘è€…"; then
                  CATEGORY_TAGS="${CATEGORY_TAGS} | \`å¼€æºåˆ›æ–°åŠ›é‡\`"
                fi
                if echo "$CONTENT" | grep -qi "ç ”ç©¶\|è®ºæ–‡\|å­¦æœ¯\|å¤§å­¦\|å®žéªŒå®¤"; then
                  CATEGORY_TAGS="${CATEGORY_TAGS} | \`å‰æ²¿ç§‘å­¦æŽ¢ç´¢\`"
                fi
                if echo "$CONTENT" | grep -qi "æœºå™¨äºº\|Robot\|äººå½¢æœºå™¨äºº\|è‡ªåŠ¨é©¾é©¶"; then
                  CATEGORY_TAGS="${CATEGORY_TAGS} | \`AIä¸Žäººç±»æœªæ¥\`"
                fi
                if echo "$CONTENT" | grep -qi "å›¾åƒç”Ÿæˆ\|æ–‡ç”Ÿå›¾\|è§†é¢‘ç”Ÿæˆ\|AIGC"; then
                  CATEGORY_TAGS="${CATEGORY_TAGS} | \`åˆ›æ„AIå·¥å…·\`"
                fi
                if echo "$CONTENT" | grep -qi "åŒ»ç–—\|åŒ»å­¦\|å¥åº·\|æ•™è‚²\|é‡‘èž"; then
                  CATEGORY_TAGS="${CATEGORY_TAGS} | \`è¡Œä¸šåº”ç”¨\`"
                fi
                if echo "$CONTENT" | grep -qi "è°·æ­Œ\|å¾®è½¯\|Meta\|è‹¹æžœ\|äºšé©¬é€Š\|ç™¾åº¦\|é˜¿é‡Œ\|è…¾è®¯"; then
                  CATEGORY_TAGS="${CATEGORY_TAGS} | \`è¡Œä¸šè‡ªç”±å‘å£°\`"
                fi
                
                # æ€»æ˜¯æ·»åŠ æ•°æ®èšåˆæ ‡ç­¾
                CATEGORY_TAGS="${CATEGORY_TAGS} | \`å…¨ç½‘æ•°æ®èšåˆ\`"
                
                # ç”ŸæˆFront Matter
                cat > "$TARGET_FILE" << EOF
          ---
          title: "AIæ´žå¯Ÿæ—¥æŠ¥ - ${DATE_PART}"
          date: ${DATE_PART}T08:00:00+08:00
          draft: false
          weight: 1
          type: docs
          sidebar:
            open: true
          description: "${DATE_PART}çš„AIè¡Œä¸šåŠ¨æ€ã€æŠ€æœ¯å‘å±•å’Œé‡è¦èµ„è®¯æ±‡æ€»"
          ---
          
          ## AIæ´žå¯Ÿæ—¥æŠ¥ ${DATE_PART}
          
          > ${CATEGORY_TAGS} | [è®¿é—®ç½‘é¡µç‰ˆâ†—ï¸](https://april8000.github.io/Hextra-AI-Insight-Daily/)
          
          EOF
                
                # æ·»åŠ åŽŸå§‹å†…å®¹ï¼ˆè·³è¿‡ç¬¬ä¸€è¡Œæ ‡é¢˜ï¼Œå› ä¸ºæˆ‘ä»¬å·²ç»æ·»åŠ äº†æ–°çš„æ ‡é¢˜ï¼‰
                tail -n +2 "$SOURCE_FILE_PATH" >> "$TARGET_FILE"
                echo "âœ… æ–‡ä»¶å·²æ›´æ–°å¹¶æ·»åŠ åˆ†ç±»æ ‡ç­¾: ${TARGET_FILE}"
                
                # åˆ›å»ºæˆ–æ›´æ–°æœˆä»½ç´¢å¼•æ–‡ä»¶
                MONTH_INDEX="${TARGET_DIR}/_index.md"
                if [ ! -f "$MONTH_INDEX" ]; then
                  cat > "$MONTH_INDEX" << EOF
          ---
          title: "${YEAR_MONTH} AIæ—¥æŠ¥"
          date: ${YEAR_MONTH}-01T00:00:00+08:00
          type: docs
          sidebar:
            open: true
          weight: 1
          description: "${YEAR_MONTH}æœˆä»½AIè¡Œä¸šåŠ¨æ€æ±‡æ€»"
          ---
          
          # ${YEAR_MONTH} AIæ´žå¯Ÿæ—¥æŠ¥
          
          æœ¬æœˆçš„AIè¡Œä¸šåŠ¨æ€å’ŒæŠ€æœ¯è¶‹åŠ¿æ±‡æ€»ï¼ŒåŒ…æ‹¬ï¼š
          - ðŸ”¥ è¡Œä¸šçƒ­ç‚¹æ–°é—»  
          - ðŸ› ï¸ æŠ€æœ¯äº§å“å‘å¸ƒ
          - ðŸ“Š å¸‚åœºæŠ•èµ„åŠ¨æ€
          - ðŸ§  å­¦æœ¯ç ”ç©¶è¿›å±•
          - ðŸ’¡ å¼€æºé¡¹ç›®æŽ¨è
          EOF
                  echo "âœ… æœˆä»½ç´¢å¼•å·²åˆ›å»º: ${MONTH_INDEX}"
                fi
              fi
            fi
          done
          
          echo "--- å¸¦åˆ†ç±»æ ‡ç­¾çš„å†…å®¹å¤„ç†å®Œæˆ ---"
          
          # æ˜¾ç¤ºæœ€ç»ˆç›®å½•ç»“æž„
          echo "=== æœ€ç»ˆç›®å½•ç»“æž„ ==="
          find content/cn -type f -name "*.md" | head -10
          
          # ç»Ÿè®¡ä¿¡æ¯
          echo "=== ç»Ÿè®¡ä¿¡æ¯ ==="
          echo "æ€»æ–‡ä»¶æ•°: $(find content/cn -name "*.md" -type f | wc -l)"
          echo "æœ€æ–°æ–‡ä»¶: $(find content/cn -name "*.md" -type f | sort | tail -3)"

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add .
          if git diff --staged --quiet; then
            echo "â„¹ï¸ æ²¡æœ‰éœ€è¦æäº¤çš„æ›´æ”¹"
          else
            git commit -m "ðŸ·ï¸ æ·»åŠ å†…è”åˆ†ç±»æ ‡ç­¾ - $(date +%Y-%m-%d-%H-%M)"
            git push
            echo "âœ… å¸¦åˆ†ç±»æ ‡ç­¾çš„å†…å®¹å·²åŒæ­¥å¹¶æŽ¨é€åˆ°ä»“åº“"
          fi

      - name: Notify completion
        if: always()
        run: |
          echo "ðŸŽ‰ å¸¦åˆ†ç±»æ ‡ç­¾çš„å†…å®¹åŒæ­¥å®Œæˆï¼"
          echo "âœ¨ æ–°åŠŸèƒ½:"
          echo "   ðŸ·ï¸ æ™ºèƒ½åˆ†ç±»æ ‡ç­¾ (æ ¹æ®å†…å®¹è‡ªåŠ¨ç”Ÿæˆ)"
          echo "   ðŸ“± ä¾§è¾¹æ å¯¼èˆª"
          echo "   ðŸŽ¨ åŽŸä½œè€…é£Žæ ¼çš„æ ‡ç­¾å±•ç¤º"
          echo "ðŸ“Š ç»Ÿè®¡ä¿¡æ¯ï¼š"
          find content/cn -name "*.md" -type f | wc -l | xargs echo "æ€»æ–‡ä»¶æ•°ï¼š"
          echo "ðŸ”— ç½‘ç«™å°†åœ¨å‡ åˆ†é’Ÿå†…è‡ªåŠ¨æ›´æ–°"
